#!/bin/bash

# This script is used to update the filenametags for lookupfile plugin, and the
# ctags & cscope database

# Default project type
PRJ_TYPE=android-bt
path_list=(
"./device/mstar/common/libraries/bluetooth/bluetoothmonitor/bluedroid/bluetooth.c"
"./device/mstar/common/preinstall/bluetooth/loadbt.sh"
"./device/mstar/common/preinstall/bluetooth/unloadbt.sh"
"./frameworks/base/core/java/android/bluetooth"
"./frameworks/base/core/tests/bluetoothtests/src/android/bluetooth"
"./frameworks/base/services/core/java/com/android/server/BluetoothManagerService.java"
"./frameworks/base/core/jni/android_bluetooth_BluetoothMonitor.cpp"
"./hardware/libhardware/include/hardware/b*"
"./hardware/qcom/bt/libbt-vendor"
"./packages/apps/Bluetooth"
"./packages/apps/Settings/src/com/android/settings/bluetooth"
"./system/bt"
"./vendor/qcom/bt_usb_driver"
)

case ${PRJ_TYPE} in
    java)
    SRC_DIR="src"
    find ${SRC_DIR}                         \
                -name ".svn" -prune         \
                -or -name ".git" -prune     \
                -or -name "*.java"          \
                > cscope.files
    ;;
    cpp)
    SRC_DIR="."
    find ${SRC_DIR}                         \
                -name ".svn" -prune         \
                -or -name ".git" -prune     \
                -or -name "*.h"             \
                -or -name "*.cpp"           \
                -or -name "*.cc"            \
                > cscope.files
    ;;
    android-bt)
        if [ -e cscope.files ]
        then
            echo find cscope.files
            rm cscope.files
        fi
        for i in "${path_list[@]}"
        do
            echo $i
            find $i  -type f                    \
                -name ".git" -prune             \
                -or -name "*.java"              \
                -or -name "*.cpp"               \
                -or -name "*.c"                 \
                -or -name "*.h"                 \
                -or -name "*.mk"                \
                -or -name "*.aidl"                \
                -or -name "Makefile"            \
                >> cscope.files
        done
    ;;
    *)
    ;;
esac

# generate tag file for lookupfile plugin
echo "!_TAG_FILE_SORTED	2	/2=foldcase/" > ./filenametags

for i in ${path_list[@]}
do
    find ${i}                         \
                -name ".svn" -prune         \
                -or -name ".git" -prune     \
                -or -type f                 \
                -printf "%f\t%p\t1\n"       \
                | sort -f >> ./filenametags
done

# Generate cscope database & tags
cscope -bkq -i cscope.files
ctags --c++-kinds=+p --fields=+iaS --extra=+q -L cscope.files

exit 0
